const fs = require('fs');
const file = 'HomeScreen.js';
let content = fs.readFileSync(file, 'utf8');

const s1 = content.indexOf('const handleToggleEnabled = async (card) => {');
const e1 = content.indexOf('const handleBulkSetEnabled = async (nextEnabled)');

const r1 = 'const handleToggleEnabled = async (card) => {\\n\t\tconst previousEnabled = normalizeEnabledValue(card.enabled);\\n\t\tconst nextEnabled = !previousEnabled;\\n\\n\t\tsetFlashcards((prev) =>\\n\t\t\tprev.map((item) =>\\n\t\t\t\titem.id === card.id ? { ...item, enabled: nextEnabled } : item,\\n\t\t\t),\\n\t\t);\\n\\n\t\ttry {\\n\t\t\tconst response = await flashcardsAPI.update(card.id, {\\n\t\t\t\tfrontText: card.front_text,\\n\t\t\t\tbackText: card.back_text,\\n\t\t\t\tenabled: nextEnabled,\\n\t\t\t});\\n\t\t\tconst responseEnabled = response?.data?.flashcard?.enabled;\\n\t\t\tif (responseEnabled !== undefined && responseEnabled !== null) {\\n\t\t\t\tconst persistedEnabled = normalizeEnabledValue(responseEnabled);\\n\t\t\t\tif (persistedEnabled !== nextEnabled) {\\n\t\t\t\t\tthrow new Error("TOGGLE_NOT_PERSISTED");\\n\t\t\t\t}\\n\t\t\t}\\n\t\t} catch (error) {\\n\t\t\tsetFlashcards((prev) =>\\n\t\t\t\tprev.map((item) =>\\n\t\t\t\t\titem.id === card.id ? { ...item, enabled: previousEnabled } : item,\\n\t\t\t\t),\\n\t\t\t);\\n\t\t\tconsole.error("Error toggling card enabled state:", error?.response?.data || error);\\n\t\t\tshowAlert?.(error?.response?.data?.message || error?.response?.data?.error || t("error") || "Error");\\n\t\t}\\n\t};\\n\\n\\t';

content = content.substring(0, s1) + r1 + content.substring(e1);
let e2 = content.indexOf('const handleBulkSetEnabled = async (nextEnabled)');
let e2_end = content.indexOf('finally {', e2);
e2_end = content.indexOf('};', e2_end) + 2;

const r2 = 'const handleBulkSetEnabled = async (nextEnabled) => {\\n\t\tconst targetFlashcards = filteredFlashcards.filter(\\n\t\t\t(card) => normalizeEnabledValue(card.enabled) !== nextEnabled,\\n\t\t);\\n\\n\t\tif (targetFlashcards.length === 0) {\\n\t\t\treturn;\\n\t\t}\\n\\n\t\tsetBulkSaving(true);\\n\t\ttry {\\n\t\t\tconst targetIdsArray = targetFlashcards.map((card) => card.id);\\n\t\t\tconst targetIds = new Set(targetIdsArray);\\n\\n\t\t\tsetFlashcards((prev) =>\\n\t\t\t\tprev.map((card) =>\\n\t\t\t\t\ttargetIds.has(card.id) ? { ...card, enabled: nextEnabled } : card,\\n\t\t\t\t),\\n\t\t\t);\\n\\n\t\t\tconst results = await Promise.allSettled(\\n\t\t\t\ttargetFlashcards.map((card) =>\\n\t\t\t\t\tflashcardsAPI.update(card.id, {\\n\t\t\t\t\t\tfrontText: card.front_text,\\n\t\t\t\t\t\tbackText: card.back_text,\\n\t\t\t\t\t\tenabled: nextEnabled,\\n\t\t\t\t\t}),\\n\t\t\t\t),\\n\t\t\t);\\n\\n\t\t\tconst failedIds = targetFlashcards\\n\t\t\t\t.filter((_, index) => {\\n\t\t\t\t\tconst result = results[index];\\n\t\t\t\t\tif (result?.status === "rejected") return true;\\n\t\t\t\t\tconst responseEnabled = result?.value?.data?.flashcard?.enabled;\\n\t\t\t\t\tif (responseEnabled === undefined || responseEnabled === null)\\n\t\t\t\t\t\treturn false;\\n\t\t\t\t\tconst persistedEnabled = normalizeEnabledValue(responseEnabled);\\n\t\t\t\t\treturn persistedEnabled !== nextEnabled;\\n\t\t\t\t})\\n\t\t\t\t.map((card) => card.id);\\n\\n\t\t\tif (failedIds.length > 0) {\\n\t\t\t\tconst failedIdSet = new Set(failedIds);\\n\t\t\t\tsetFlashcards((prev) =>\\n\t\t\t\t\tprev.map((card) =>\\n\t\t\t\t\t\tfailedIdSet.has(card.id)\\n\t\t\t\t\t\t\t? {\\n\t\t\t\t\t\t\t\t\t...card,\\n\t\t\t\t\t\t\t\t\tenabled: normalizeEnabledValue(card.enabled) !== nextEnabled ? !nextEnabled : card.enabled,\\n\t\t\t\t\t\t\t  }\\n\t\t\t\t\t\t\t: card,\\n\t\t\t\t\t),\\n\t\t\t\t);\\n\\n\t\t\t\tif (failedIds.length === targetFlashcards.length) {\\n\t\t\t\t\tshowAlert?.(t("error") || "Error");\\n\t\t\t\t}\\n\t\t\t}\\n\t\t} catch (error) {\\n\t\t\tconsole.error("Error bulk updating flashcards:", error);\\n\t\t\tsetFlashcards((prev) =>\\n\t\t\t\tprev.map((card) =>\\n\t\t\t\t\ttargetFlashcards.find((t) => t.id === card.id)\\n\t\t\t\t\t\t? { ...card, enabled: !nextEnabled }\\n\t\t\t\t\t\t: card,\\n\t\t\t\t),\\n\t\t\t);\\n\t\t\tshowAlert?.(error?.response?.data?.message || error?.response?.data?.error || t("error") || "Error");\\n\t\t} finally {\\n\t\t\tsetBulkSaving(false);\\n\t\t}\\n\t};\\n';

content = content.substring(0, e2) + r2 + content.substring(e2_end);
fs.writeFileSync(file, content);
console.log('Done!');
